# Generated by Django 4.1 on 2022-08-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0003_alter_note_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AddField(
            model_name='note',
            name='sem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='usn',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
