# Generated by Django 4.1 on 2022-08-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0004_remove_note_id_note_sem_alter_note_usn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('usn', models.CharField(max_length=50, primary_key='True', serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('sem', models.CharField(default='', max_length=50)),
                ('num', models.CharField(default='', max_length=50)),
                ('mail', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='note',
        ),
    ]
